### ISSUE TITLE
Implement CORS

### ISSUE THREAD

**Issue by DazWilkin** [sudorandom/fauxrpc#16]
Please consider adding [CORS](https://connectrpc.com/docs/go/deployment/#cors) so that browser clients may (also) use gRPC-Web against FauxRPC.

Per this issue [comment](https://github.com/sudorandom/fauxrpc/issues/15#issuecomment-2477511105).

**Comment by sudorandom** [comment]
This has been added and released as [v0.2.0](https://github.com/sudorandom/fauxrpc/releases/tag/v0.2.0). Thanks for the request!
