### ISSUE TITLE
Generate fake response based on proto

### ISSUE THREAD

**Issue by ibrhmkoz** [sudorandom/fauxrpc#19]
I've examined a test in the repo and run it but it doesn't work in the intended way, resulting the test to fail. I guess the intended behavior was to produce fake data but this generates an empty string:

```go
	// Now we can call the service and generated data will be returned
	t.Run("using the default generated responses", func(t *testing.T) {
		elizaClient := elizav1connect.NewElizaServiceClient(http.DefaultClient, baseURL)
		resp, err := elizaClient.Say(ctx, connect.NewRequest(&elizav1.SayRequest{
			Sentence: "testing!",
		}))
		if err != nil {
			t.Fatalf("unable to call eliza.Say: %s", err)
		}
		if len(resp.Msg.Sentence) == 0 {
			t.Fatal("sentence should not be empty, but it was")
		}
	})
```

Can we expose an API to produce fake data if this isn't a bug?

**Comment by sudorandom** [comment]
I was just looking into this. Changes in 0.3.0 broke this behavior. I pushed a change that should fix it. It's v0.3.1. Make sure you pull the latest docker image: `docker pull docker.io/sudorandom/fauxrpc:latest`

**Comment by sudorandom** [comment]
Let me know if you're still hitting issues. If so, please re-open this!
